services: 
  web:  # Apache and PHP service
    container_name: php-apache   
    build: 
      context: ./php/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
    networks:
      - webnet

  db:    
    container_name: mydb
    image: mysql:8.4
    restart: always
    # command: ["mysqld", "--mysql-native-password=ON"]
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db      
    ports:
      - "8081:80"
    networks:
      - webnet

networks:
  webnet: